### ISSUE TITLE
variable "records" returns a type error

### ISSUE THREAD

**Issue by tcarrondo** [tcarrondo/terraform-cloudflare-zone#9]
I'm getting this error, on terraform plan:

`Error: Invalid value for module argument
[...]
The given value is not suitable for child module variable "records" defined at .terraform/modules/.../variables.tf:25,1-19: map of any single type required.`

**Comment by abacao** [comment]
Thios solves this issue?
https://github.com/tcarrondo/terraform-cloudflare-zone/pull/11

**Comment by tcarrondo** [comment]
yes
